#ifndef PMDSKY_EVENT_FLAG_SIZE
#define PMDSKY_EVENT_FLAG_SIZE

void sub_0204B028();
extern const u8 EVENT_FLAG_SIZE_DEBUG_MSG[];
// extern const u8 EVENT_FLAG_EXPANSION_ERROR[];

#endif //PMDSKY_EVENT_FLAG_SIZE